alias lnsilk='ln -s /usr/local/etc/silk/'
alias lnyui='ln -s /usr/local/etc/yui_2.5.1/ ./yui'
alias lnckeditor='ln -s /home/jared/Work/code/ck/editor/4.1.2/ ./CKEditor'
alias lnckfinder='ln -s /home/jared/Work/code/ck/finder/ckfinder-2.3.1/ ./CKFinder'
alias lnzend='ln -s /usr/local/etc/ZendFramework-1.12.3/library/Zend/ ./Zend'
alias lnbyte='ln -s /home/jared/Work/code/byte/lib/byte/ ./byte'
alias lncms='ln -s /home/jared/Work/code/cms/cms/lib/cms/ ./'
alias lnbsa='ln -s /home/jared/Work/code/byte-shared-assets/ ./byte-shared-assets'
alias lnrtvas='ln -s /home/jared/Work/code/rtvagentsites/lib/rtvAS/ ./rtvAS'
alias lnfss='ln -s /home/jared/Work/code/fadeslideshow/fadeslideshow.js ./'
alias devsource='source /home/jared/code/dev/env/bin/activate'
alias howdoi='howdoi -c'
alias g='git'
alias tmux="TERM=screen-256color-bce tmux"
alias byte='python /home/jared/code/byte/byte.py'
alias focuschrome='if test $(wmctrl -vxa chrome 2>&1 | wc -l) -eq 1; then google-chrome; fi'
