alias lnsilk='ln -s /home/jared/Work/code/silk/ ./silk'
alias lnyui='ln -s /home/jared/Work/code/yui_2.5.1/ ./yui'
alias lnckeditor='ln -s /home/jared/Work/code/ck/editor/4.1.2/ ./CKEditor'
alias lnckfinder='ln -s /home/jared/Work/code/ck/finder/ckfinder-2.3.1/ ./CKFinder'
alias lnzend='ln -s /home/jared/Work/code/Zend ./Zend'
alias lnbyte='ln -s /home/jared/Work/code/byte/lib/byte/ ./byte'
alias lncms='ln -s /home/jared/Work/code/cms/lib/cms/ ./'
alias lnbsa='ln -s /home/jared/Work/code/byte-shared-assets/ ./byte-shared-assets'
alias lnrtvds='ln -s /home/jared/Work/code/rtvdealersites/trunk/lib/rtvDS/ ./rtvDS'
alias lnrtvas='ln -s /home/jared/Work/code/rtvagentsites/lib/rtvAS/ ./rtvAS'
alias lnfss='ln -s /home/jared/Work/code/fadeslideshow/fadeslideshow.js ./'
alias lnassets='ln -s /home/jared/Work/code/assets/ ./'
alias devsource='source /home/jared/code/dev/env/bin/activate'
alias howdoi='howdoi -c'
alias g='git'
alias tmux="TERM=screen-256color-bce tmux"
alias byte='python /home/jared/code/byte/byte.py'
alias focuschrome='if test $(wmctrl -vxa chrome 2>&1 | wc -l) -eq 1; then google-chrome; fi'
alias mysql_bytepages='mysql -h 23.253.63.76 -u byteadmin -p'
alias mysql_rsweb2='mysql -h rsweb2.bytepro.net -u byteadmin -p'
alias mysql_localhost='mysql -u root'
alias muds='z tintin && tmux -f ~/.tmux_mud.conf'
alias mtr='mtr --curses'
alias ag='ag --pager=less'
alias editglobal='vim local/config/global.php'
alias editcms='vim local/config/cms.php'
